name: powerd6
description: A collection of models to support the powerd6 ruleset.
version: 1.0.1
homepage: https://github.com/powerd6/powerd6
issue_tracker: https://github.com/powerd6/powerd6/issues

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  collection: ^1.16.0
  args: ^2.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  coverage: ^1.2.0
  mocktail: ^0.3.0
